version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: medicheck-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: medicheck-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    container_name: medicheck-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
